# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes:
      # Persist PostgreSQL data
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: ascendance_db
    ports:
      - 5432:5432

volumes:
  postgres_data:
    driver: local
